### PR TITLE
WIP: Guest book compilation

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
Addresses #10

### CODE REVIEW

**Comment by pipermerriam** [comment]
This has been fun to watch coming along.  Will you ping us when you feel this is ready for someone to give it :eyes: 

Also, you might start thinking about how you can break this up into smaller pieces. The current size of this PR is a bit too large to be effectively reviewed.

**Comment by g-r-a-n-t** [comment]
Thanks for checking this out @pipermerriam. I think there are a few components that could be split out and reviewed independently after I do some cleanup. Here's what I'm thinking:

First create two PRs that include support for...
- Function only ABIs.
- Vyper to Yul compilation for very simple contracts.

Then create another PR with the Vyper to bytecode compiler and module-level tests. The module tests use [rust-evm](https://docs.rs/evm/0.14.2/evm/) to create and execute contracts and [ethabi](https://docs.rs/ethabi/11.0.0/ethabi/) to form contract input.

Currently, everything mentioned above is working.

After these are all merged, support for maps, arrays, events, and other features used in `guest_book.vy` could be added in separate PRs.

**Comment by davesque** [comment]
Hey Grant.  I also wanted to jump in and say that the work you're doing is really amazing.  You're doing a huge amount to prove the viability of this project.  When I initially began work on Rust Vyper, I had serious questions as to whether or not it would really pan out.  I'm really thrilled that you've been able to move so quickly on top of the work that was done on the parser.

**Comment by g-r-a-n-t** [comment]
I'm picking this apart and creating smaller PRs.

**Comment by g-r-a-n-t** [comment]
I'm picking this apart and creating smaller PRs.

**Pull request closed without merging**
